version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # To avoid overwriting node_modules from the host
    environment:
      - CHOKIDAR_USEPOLLING=true  # Optionally: improves hot-reloading
